spring:
  profiles:
    active: local #default
    group:
      local:
        - common
        - security
      dev:
        - common
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update


value: 'from local'