spring:
  profiles:
    active: local #default
    group:
      local:
        - common
        - security
      dev:
        - common
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  session:
    storage-type: redis

#스웨거 경로 에러 해결을 위한 설정
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
value: 'from local'